# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        "%kernel.project_dir%/app/Resources/views": ~
    globals:
        public_registration_enabled: '%app.public_registration_enabled%'
