imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
    mailer:
        dsn: 'null://null'

web_profiler:
    toolbar: false
    intercept_redirects: false

services:
    test.doctrine.orm.entity_manager:
        alias: doctrine.orm.entity_manager
        public: true
