imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@DevlabsSportifyBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    # application parameters
    football_api.name: football_data_org
    football_api.base_uri: http://api.football-data.org/v2
    app.registration_confirmation_enabled: true
    app.oauth_access_token_lifetime: 7776000 # 90 days in seconds
    app.scoring.default_outcome_points: 2
    app.scoring.default_exact_points: 5

framework:
    #esi:             ~
    translator: { fallbacks: [en] }
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.project_dir%/app/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      ~
    property_info:
        with_constructor_extractor: false
    mailer:
        dsn: "%mailer_dsn%"
#    serializer:
#        enabled: true
#        enable_annotations: true
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.project_dir%/var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        "%kernel.project_dir%/app/Resources/views": ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        server_version: '8.0'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collation: utf8mb4_unicode_ci
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/app/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
            DevlabsSportifyBundle:
                is_bundle: false
                type: xml
                dir: "%kernel.project_dir%/app/config/doctrine"
                prefix: 'Devlabs\SportifyBundle\Entity'
                alias: DevlabsSportifyBundle

jms_serializer:
    metadata:
        directories:
            DevlabsSportifyBundle:
                path: "%kernel.project_dir%/app/config/serializer/DevlabsSportify"
                namespace_prefix: "Devlabs\\SportifyBundle"

bazinga_hateoas:
    metadata:
        cache: file
        file_cache:
            dir: "%kernel.cache_dir%/hateoas"
