devlabs_sportify:
    resource: routing_web.yml

devlabs_sportify_api:
    type:     rest
    resource: "@DevlabsSportifyBundle/Controller/Api"
    defaults: {_format: json}
    prefix:   /api/

fos_user_security_login:
    path: /login
    defaults: { _controller: Devlabs\SportifyBundle\Controller\SecurityController::loginAction }
    methods: [GET]

fos_user_security_check:
    path: /login_check
    defaults: { _controller: Devlabs\SportifyBundle\Controller\SecurityController::checkAction }
    methods: [POST]

fos_user_security_logout:
    path: /logout
    defaults: { _controller: Devlabs\SportifyBundle\Controller\SecurityController::logoutAction }
    methods: [GET]

fos_user_registration_register:
    path: /register/
    defaults: { _controller: Devlabs\SportifyBundle\Controller\RegistrationController::registerAction }
    methods: [GET, POST]

fos_user_registration_check_email:
    path: /register/check-email
    defaults: { _controller: Devlabs\SportifyBundle\Controller\RegistrationController::checkEmailAction }
    methods: [GET]

fos_user_registration_confirm:
    path: /register/confirm/{token}
    defaults: { _controller: Devlabs\SportifyBundle\Controller\RegistrationController::confirmAction }
    methods: [GET]

fos_user_registration_confirmed:
    path: /register/confirmed
    defaults: { _controller: Devlabs\SportifyBundle\Controller\RegistrationController::confirmedAction }
    methods: [GET]

fos_user_resetting_request:
    path: /resetting/request
    defaults: { _controller: Devlabs\SportifyBundle\Controller\ResettingController::requestAction }
    methods: [GET]

fos_user_resetting_send_email:
    path: /resetting/send-email
    defaults: { _controller: Devlabs\SportifyBundle\Controller\ResettingController::sendEmailAction }
    methods: [POST]

fos_user_resetting_check_email:
    path: /resetting/check-email
    defaults: { _controller: Devlabs\SportifyBundle\Controller\ResettingController::checkEmailAction }
    methods: [GET]

fos_user_resetting_reset:
    path: /resetting/reset/{token}
    defaults: { _controller: Devlabs\SportifyBundle\Controller\ResettingController::resetAction }
    methods: [GET, POST]

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

devlabs_sportify_api_root:
    path: /api
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: nelmio_api_doc_index
        permanent: true