monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
            channels:     ['!prediction', '!operations']
        operational_warnings:
            type:     stream
            path:     "%kernel.logs_dir%/%kernel.environment%.log"
            level:    warning
            channels: ['operations']
        prediction_rejections:
            type:     stream
            path:     "%kernel.logs_dir%/%kernel.environment%.log"
            level:    warning
            channels: ['prediction']
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
