Devlabs\SportifyBundle\Entity\Team:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: name

Devlabs\SportifyBundle\Entity\Prediction:
    properties:
        homeGoals:
            - Type:
                type: integer
                message: 'The value {{ value }} is not a valid {{ type }}.'
        awayGoals:
            - Type:
                type: integer
                message: 'The value {{ value }} is not a valid {{ type }}.'
