<?php

namespace Devlabs\SportifyBundle\Entity;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get the first team for a tournament from the DB
     *
     * @param Tournament $tournament
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getFirstByTournament(Tournament $tournament)
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('tm')
            ->from(Team::class, 'tm')
            ->join('tm.tournaments', 'tr')
            ->where('tr.id = :tournament_id')
            ->setParameter('tournament_id', $tournament->getId())
            ->setMaxResults(1);

        try {
            return $query->getQuery()->getSingleResult();
        }
        catch(\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    /**
     * Get all teams for given tournament
     *
     * @param Tournament $tournament
     * @return array
     */
    public function getAllByTournament(Tournament $tournament)
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('tm')
            ->from(Team::class, 'tm')
            ->join('tm.tournaments', 'tr')
            ->where('tr.id = :tournament_id')
            ->setParameter('tournament_id', $tournament->getId())
            ->getQuery()
            ->getResult();
    }
}
